/* Unit 06 — NIE Grade 12 Chemistry Resource Book (2019), printed pp.125–179.
   Original educational summary, not a transcription. Sinhala / English / Tamil kept separate. */
window.U6_CHAPTERS=[
{ref:"4.1",pages:"126–130",name:["1 වන කාණ්ඩය — ක්ෂාර ලෝහ","Group 1 — alkali metals","தொகுதி 1 — கார உலோகங்கள்"],
 intro:["Li සිට Cs දක්වා පරමාණුක අරය, අයනීකරණ ශක්තිය, ජලය හා ඔක්සිජන් සමඟ ප්‍රතික්‍රියා, ලවණවල තාප ස්ථායීතාව සහ පහන් සිළු පරීක්ෂාව සංසන්දනය කරන්න.","Compare radii, ionization energy, reactions with water and oxygen, thermal stability and flame colours from Li to Cs.","Li முதல் Cs வரை ஆரம், அயனியாக்க ஆற்றல், நீர் மற்றும் ஒட்சிசனுடனான தாக்கங்கள், வெப்ப நிலைத்தன்மை மற்றும் சுவாலைச் சோதனை ஆகியவற்றை ஒப்பிடுக."],
 photos:["Flammenfärbung Natrium (Na).jpg","Flammenfärbung Kalium (K).jpg"],video:"kJaqhpZVQdw",
 steps:[
 {t:["ඉලෙක්ට්‍රෝන වින්‍යාසය හා ප්‍රවණතා","Electronic configuration and trends","இலத்திரன் அமைப்பும் போக்குகளும்"],d:["අවසන් කවචයේ ns¹ ඉලෙක්ට්‍රෝනයක් ඇත. පහළට යන විට පරමාණුක අරය වැඩි වී පළමු අයනීකරණ ශක්තිය අඩු වේ. +1 ඔක්සිකරණ අවස්ථාව බහුලය.","The outer shell is ns¹. Atomic radius increases and first ionization energy decreases down the group; +1 is the usual oxidation state.","வெளிக்கூடு ns¹ ஆகும். கீழே செல்ல ஆரம் அதிகரித்து முதல் அயனியாக்க ஆற்றல் குறைகிறது; +1 பொதுவான ஒட்சியேற்ற நிலையாகும்."],eq:"Li < Na < K < Rb < Cs : ප්‍රතික්‍රියාශීලීතාව ↑"},
 {t:["ජලය හා ඔක්සිජන් සමඟ ප්‍රතික්‍රියා","Water and oxygen reactions","நீருடனும் ஒட்சிசனுடனும் தாக்கங்கள்"],d:["ජලය සමඟ හයිඩ්‍රොක්සයිඩ සහ H₂ ලැබේ; පහළට යන විට ප්‍රතික්‍රියාව වේගවත් වේ. Li ප්‍රධාන වශයෙන් ඔක්සයිඩයත්, Na පෙරොක්සයිඩයත්, K සුපර්ඔක්සයිඩයත් සාදයි.","Water forms hydroxides and hydrogen; reactivity increases down the group. Li favours oxide, Na peroxide and K superoxide in excess oxygen.","நீருடன் ஐதரொட்சைடும் H₂ வாயுவும் உருவாகின்றன. Li ஒட்சைடு, Na பெரொட்சைடு, K சுப்பர் ஒட்சைடு உருவாக்கும்."],eq:"2Na + 2H₂O → 2NaOH + H₂  |  2Na + O₂ → Na₂O₂  |  K + O₂ → KO₂"},
 {t:["ලවණවල තාප ස්ථායීතාව","Thermal stability of salts","உப்புகளின் வெப்ப நிலைத்தன்மை"],d:["LiNO₃ රත් කළ විට Li₂O, NO₂ සහ O₂ සෑදේ. අනෙක් 1 වන කාණ්ඩ නයිට්‍රේට නයිට්‍රයිට හා O₂ බවට වියෝජනය වේ. Li₂CO₃ අනෙක් කාණ්ඩීය කාබනේටවලට වඩා පහසුවෙන් වියෝජනය වේ.","Heating LiNO₃ gives Li₂O, NO₂ and O₂; other Group 1 nitrates give nitrite and oxygen. Li₂CO₃ decomposes relatively readily.","LiNO₃ சூடுபடுத்தினால் Li₂O, NO₂, O₂ கிடைக்கும்; மற்ற நைட்ரேட்டுகள் நைட்ரைட், O₂ ஆகும். Li₂CO₃ இலகுவாகப் பகுப்படைகிறது."],eq:"4LiNO₃ → 2Li₂O + 4NO₂ + O₂  |  2KNO₃ → 2KNO₂ + O₂"},
 {t:["ජලද්‍රාව්‍යතාව හා පහන් සිළු","Solubility and flame colours","கரைதிறனும் சுவாலை நிறங்களும்"],d:["බොහෝ 1 වන කාණ්ඩ ලවණ ජලද්‍රාව්‍යය; LiF, Li₂CO₃ හා Li₃PO₄ සීමිත ද්‍රාව්‍යතාව පෙන්වයි. Li තද රතු, Na කහ, K ලා දම් වර්ණ ලබා දෙයි.","Most Group 1 salts dissolve; LiF, Li₂CO₃ and Li₃PO₄ are exceptions. Li gives crimson, Na yellow and K lilac flames.","பெரும்பாலான உப்புகள் கரையும்; LiF, Li₂CO₃, Li₃PO₄ விதிவிலக்குகள். Li சிவப்பு, Na மஞ்சள், K ஊதா சுவாலைத் தரும்."],eq:"Li : රතු  |  Na : කහ  |  K : ලා දම්"}],
 qs:[
 ["1 වන කාණ්ඩයේ බාහිර ඉලෙක්ට්‍රෝන වින්‍යාසය?","Outer-shell configuration of Group 1?","தொகுதி 1 வெளிக்கூட்டு அமைப்பு?",["ns¹","ns²","ns²np¹","ns²np⁶"],0,"ක්ෂාර ලෝහවල බාහිර කවචය ns¹ වේ."],
 ["ජලය සමඟ ප්‍රතික්‍රියාවෙන් ලැබෙන වායුව?","Gas evolved with water?","நீருடனான தாக்கத்தில் வெளிப்படும் வாயு?",["O₂","H₂","N₂","Cl₂"],1,"2M + 2H₂O → 2MOH + H₂."],
 ["අතිරික්ත ඔක්සිජන් සමඟ K හි ප්‍රධාන ඵලය?","Major K product in excess oxygen?","அதிக O₂ இல் K தரும் முக்கிய விளைவு?",["K₂O","K₂O₂","KO₂","KOH"],2,"K සුපර්ඔක්සයිඩය KO₂ සෑදේ."],
 ["රත් කළ LiNO₃ හි ඵලයකි?","A product from heating LiNO₃?","LiNO₃ ஐ சூடாக்கும்போது கிடைப்பது?",["Li₂O","LiNO₂ පමණි","NH₃","LiH"],0,"LiNO₃ → Li₂O, NO₂ සහ O₂."],
 ["Na පහන් සිළු වර්ණය?","Na flame-test colour?","Na சுவாலை நிறம்?",["රතු / red","කහ / yellow","කොළ / green","නිල් / blue"],1,"Na ප්‍රබල කහ පැහැයක් ලබා දෙයි."]
 ]},
{ref:"4.2",pages:"131–134",name:["2 වන කාණ්ඩය — ක්ෂාරීය පාංශු ලෝහ","Group 2 — alkaline earth metals","தொகுதி 2 — கார மண் உலோகங்கள்"],
 intro:["Be, Mg, Ca, Sr, Ba හි +2 ඔක්සිකරණ අවස්ථාව, ජලය සමඟ ක්‍රියා, නයිට්‍රේට/කාබනේට වියෝජනය සහ ලවණ ද්‍රාව්‍යතාව පරීක්ෂා කරන්න.","Examine the +2 oxidation state, water reactions, nitrate/carbonate decomposition and solubility patterns for Be–Ba.","Be–Ba தனிமங்களின் +2 நிலை, நீருடனான தாக்கம், நைட்ரேட்/கார்பனேட் சிதைவு, கரைதிறன் போக்குகளை ஆராய்க."],
 photos:["Flammenfärbung Calcium (Ca).jpg","Flammenfärbung Strontium (Sr).jpg"],video:"zDoLZHZSulE",
 steps:[
 {t:["ns² හා +2 ඔක්සිකරණය","ns² and +2 oxidation state","ns² மற்றும் +2 ஒட்சியேற்ற நிலை"],d:["2 වන කාණ්ඩයේ බාහිර වින්‍යාසය ns² ය. +2 කැටායන සාදන අතර ප්‍රතික්‍රියාශීලීතාව සාමාන්‍යයෙන් පහළට වැඩි වේ. BeO සහ Be(OH)₂ උභයගුණී වේ.","The valence configuration is ns²; +2 cations are common. BeO and Be(OH)₂ are amphoteric; reactivity generally increases down the group.","வெளிக்கூடு ns²; +2 அயன்கள் பொதுவாக உருவாகின்றன. BeO, Be(OH)₂ இருபண்புடையவை."],eq:"M → M²⁺ + 2e⁻"},
 {t:["ජලය හා නයිට්‍රජන් ප්‍රතික්‍රියා","Water and nitrogen","நீர் மற்றும் நைதரசன் தாக்கங்கள்"],d:["Be ජලය සමඟ නොක්‍රියා කරයි. Mg උණු ජලය සමඟ සෙමින් ක්‍රියා කරයි; Ca, Sr, Ba සිසිල් ජලය සමඟ ප්‍රතික්‍රියා කරයි. Mg වැනි ලෝහ N₂ සමඟ නයිට්‍රයිඩ සාදයි.","Be does not react with water under normal conditions; Mg reacts slowly with hot water, and Ca/Sr/Ba with cold water. Nitrides may form with nitrogen.","Be சாதாரண நீருடன் தாக்கமில்லை. Mg சூடான நீருடனும் Ca/Sr/Ba குளிர்ந்த நீருடனும் தாக்குகின்றன."],eq:"Ca + 2H₂O → Ca(OH)₂ + H₂  |  3Mg + N₂ → Mg₃N₂"},
 {t:["නයිට්‍රේට හා කාබනේට වියෝජනය","Nitrate and carbonate decomposition","நைட்ரேட் மற்றும் கார்பனேட் சிதைவு"],d:["2 වන කාණ්ඩයේ නයිට්‍රේට ඔක්සයිඩ, NO₂ සහ O₂ බවට බිඳේ. කාබනේට MO හා CO₂ බවට වියෝජනය වන අතර පහළට තාප ස්ථායීතාව වැඩි වේ.","Group 2 nitrates form metal oxides, NO₂ and O₂ on heating. Carbonates form MO + CO₂; thermal stability increases down the group.","தொகுதி 2 நைட்ரேட்டுகள் MO, NO₂, O₂ தரும். கார்பனேட்டுகள் MO, CO₂ தரும்; கீழே செல்ல வெப்ப நிலைத்தன்மை அதிகரிக்கிறது."],eq:"2Mg(NO₃)₂ → 2MgO + 4NO₂ + O₂  |  CaCO₃ → CaO + CO₂"},
 {t:["ද්‍රාව්‍යතාව, වර්ණ හා පරීක්ෂණ","Solubility and flame tests","கரைதிறனும் சுவாலைச் சோதனையும்"],d:["සල්ෆේටවල ජලද්‍රාව්‍යතාව MgSO₄ සිට BaSO₄ දක්වා අඩු වන අතර හයිඩ්‍රොක්සයිඩවල ද්‍රාව්‍යතාව පහළට වැඩි වේ. Ca තැඹිලි-රතු, Sr තද රතු, Ba කහ-කොළ පහන් සිළු දක්වයි.","Sulfates become less soluble towards BaSO₄; hydroxides generally more soluble. Ca gives orange-red, Sr crimson and Ba apple-green flames.","MgSO₄ முதல் BaSO₄ வரை சல்பேட் கரைதிறன் குறையும்; ஐதரொட்சைடு கரைதிறன் கூடும். Ca செம்மஞ்சள், Sr கருஞ்சிவப்பு, Ba மஞ்சள்-பச்சை."],eq:"MgSO₄ → CaSO₄ → SrSO₄ → BaSO₄ : ද්‍රාව්‍යතාව ↓"}],
 qs:[
 ["2 වන කාණ්ඩයේ බාහිර වින්‍යාසය?","Group 2 valence configuration?","தொகுதி 2 வெளிக்கூடு?",["ns¹","ns²","ns²np⁵","nd⁶"],1,"2 වන කාණ්ඩයට ns² වේ."],
 ["සාමාන්‍ය තත්ත්වයේ ජලය සමඟ ප්‍රතික්‍රියා නොකරන ලෝහය?","Metal not reacting with water normally?","சாதாரண நீருடன் தாக்கமற்ற உலோகம்?",["Ca","Sr","Be","Ba"],2,"Be මත ආරක්ෂක ස්තරයක් ඇති අතර ජලය සමඟ ප්‍රතික්‍රියා නොකරයි."],
 ["CaCO₃ උණු කළ විට නිපදෙන වායුව?","Gas from heating CaCO₃?","CaCO₃ வெப்பச் சிதைவில் வாயு?",["H₂","CO₂","NO₂","NH₃"],1,"CaCO₃ → CaO + CO₂."],
 ["පහළට සල්ෆේටවල ද්‍රාව්‍යතාව?","Sulfate solubility down Group 2?","தொகுதி 2 இல் சல்பேட் கரைதிறன்?",["වැඩිවේ / increases","අඩුවේ / decreases","නොවෙනස් / unchanged","අහඹු / random"],1,"BaSO₄ ඉතා අඩු ද්‍රාව්‍යතාවකින් යුක්තය."],
 ["Ba පහන් සිළු වර්ණය?","Ba flame colour?","Ba சுவாலை நிறம்?",["කහ-කොළ / yellow-green","දම් / lilac","නිල් / blue","තද රතු / crimson"],0,"Ba හි කහ-කොළ වර්ණය ලක්ෂණිකය."]
 ]},
{ref:"4.3",pages:"135–136",name:["13 වන කාණ්ඩය — ඇලුමිනියම්","Group 13 — aluminium","தொகுதி 13 — அலுமினியம்"],
 intro:["B හා Al හි වෙනස්කම්, Al₂O₃ ආරක්ෂක ස්තරය, උභයගුණී Al(OH)₃, හයිඩ්‍රොක්සෝ සංකීර්ණ සහ Al₂Cl₆ ව්‍යුහය ඉගෙනගන්න.","Compare B and Al, protective Al₂O₃ film, amphoteric hydroxide, hydroxo complex ions and the Al₂Cl₆ dimer.","B மற்றும் Al வேறுபாடுகள், பாதுகாப்பான Al₂O₃ படலம், இருபண்புடைய Al(OH)₃ மற்றும் Al₂Cl₆ வடிவத்தைப் படிக்கவும்."],
 photos:["Aluminium metal pieces.jpg","Aluminum samples.png"],video:"rwZWaCcBJb8",
 steps:[
 {t:["13 වන කාණ්ඩයේ වින්‍යාසය","Group 13 configuration","தொகுதி 13 அமைப்பு"],d:["ns²np¹ වින්‍යාසය ඇති කාණ්ඩයේ B ලෝහාලෝහයක් වන අතර Al ලෝහයකි. +3 ඔක්සිකරණ අවස්ථාව බහුලය. B හි සහසංයුජ ස්වභාවය ප්‍රබලය.","Group 13 has ns²np¹; B is a metalloid and Al is a metal. The +3 oxidation state is common and B is largely covalent.","ns²np¹ அமைப்புடைய தொகுதியில் B உலோகப்போலி; Al உலோகம். +3 நிலை பொதுவானது."],eq:"B, Al, Ga, In, Tl  •  ns²np¹"},
 {t:["ආරක්ෂක ඔක්සයිඩ ස්තරය","Protective oxide film","பாதுகாக்கும் ஒட்சைடு படலம்"],d:["ඇලුමිනියම් මත සිහින් Al₂O₃ පටලයක් සෑදී තවදුරටත් ඔක්සිකරණය වීම වැළැක්වේ. O₂, හේලජන, අම්ල සහ ප්‍රබල භෂ්ම සමඟ සුදුසු තත්ත්වවලදී ප්‍රතික්‍රියා කරයි.","A thin adherent Al₂O₃ layer protects aluminium. It reacts under suitable conditions with oxygen, halogens, acids and strong bases.","Al மேற்பரப்பில் உருவாகும் Al₂O₃ படலம் மேலும் ஒட்சியேற்றத்தைத் தடுக்கிறது. அமிலம், வலுவான காரங்களுடன் தாக்கும்."],eq:"4Al + 3O₂ → 2Al₂O₃"},
 {t:["උභයගුණී හයිඩ්‍රොක්සයිඩය","Amphoteric hydroxide","இருபண்புடைய ஐதரொட்சைடு"],d:["Al³⁺ ද්‍රාවණයට OH⁻ එකතු කළ විට සුදු ජෙලටිනීය Al(OH)₃ අවක්ෂේපයක් සෑදී අතිරික්ත OH⁻ තුළ [Al(OH)₄]⁻ බවට දියවේ. උභයගුණී බව හඳුනාගැනීමේ වැදගත් කරුණකි.","Al³⁺ gives a white gelatinous Al(OH)₃ precipitate; excess OH⁻ dissolves it as [Al(OH)₄]⁻. This illustrates amphoterism.","Al³⁺ உடன் OH⁻ சேர்க்க வெள்ளை Al(OH)₃ வீழ்படிவு; அதிக OH⁻ இல் [Al(OH)₄]⁻ ஆகக் கரையும்."],eq:"Al³⁺ + 3OH⁻ → Al(OH)₃↓  |  Al(OH)₃ + OH⁻ → [Al(OH)₄]⁻"},
 {t:["ඇලුමිනියම් ක්ලෝරයිඩයේ ද්විඅණුව","Al₂Cl₆ dimer","Al₂Cl₆ இரட்டையணு"],d:["වායු අවස්ථාවේ AlCl₃ ඉලෙක්ට්‍රෝන ඌන ලුවිස් අම්ලයක් ලෙස ක්‍රියා කර පාලක Cl පරමාණු හරහා Al₂Cl₆ ද්විඅණුව සාදයි. ජලීය Al³⁺ සජල සංකීර්ණ ලෙස පවතී.","Electron-deficient AlCl₃ dimerizes in the gas phase to Al₂Cl₆ via bridging chlorides. Aqueous Al³⁺ is hydrated.","இலத்திரன் குறைவுடைய AlCl₃, பாலமாகும் Cl வழியாக Al₂Cl₆ இரட்டையணுவாகும். நீரில் Al³⁺ நீரேற்றப்பட்டிருக்கும்."],eq:"2AlCl₃ ⇌ Al₂Cl₆"}],
 qs:[
 ["13 කාණ්ඩයේ බාහිර වින්‍යාසය?","Group 13 outer configuration?","தொகுதி 13 வெளிக்கூடு?",["ns²np¹","ns²np²","ns¹","ns²np⁶"],0,"13 වන කාණ්ඩයේ ns²np¹."],
 ["Al ආරක්ෂා කරන මතුපිට ස්තරය?","Protective layer on aluminium?","Al மேற்பரப்பு பாதுகாப்புப் படலம்?",["AlCl₃","Al₂O₃","Al(OH)₃ පමණි","AlN"],1,"Al₂O₃ පටලය තවදුරටත් ක්‍රියා කිරීම සීමා කරයි."],
 ["අතිරික්ත OH⁻ තුළ දියවන අවක්ෂේපය?","Precipitate soluble in excess OH⁻?","அதிக OH⁻ இல் கரையும் வீழ்படிவு?",["BaSO₄","AgCl","Al(OH)₃","CaCO₃"],2,"Al(OH)₃ → [Al(OH)₄]⁻."],
 ["Al³⁺ හා 3OH⁻ වල ඵලය?","Product of Al³⁺ + 3OH⁻?","Al³⁺ + 3OH⁻ விளைவு?",["Al(OH)₃","Al₂O₃","AlCl₃","AlH₃"],0,"සුදු Al(OH)₃ අවක්ෂේපය සෑදේ."],
 ["AlCl₃ ද්විඅණුවේ සූත්‍රය?","Dimeric formula of AlCl₃?","AlCl₃ இரட்டையணு வாய்ப்பாடு?",["AlCl₆","Al₂Cl₃","Al₂Cl₆","Al₃Cl₂"],2,"පාලක ක්ලෝරයිඩ සහිත Al₂Cl₆ ද්විඅණුව සෑදේ."]
 ]},
{ref:"4.4",pages:"136–139",name:["14 වන කාණ්ඩය — කාබන් හා එහි සංයෝග","Group 14 — carbon chemistry","தொகுதி 14 — காபன் வேதியியல்"],
 intro:["දියමන්ති, මිනිරන්, C₆₀, CO/CO₂ සහ කාබොනික් අම්ලයේ ව්‍යුහ සහ ගුණ පැහැදිලි කරගන්න.","Understand diamond, graphite, C₆₀, CO/CO₂ and carbonic acid.","வைரம், கிராஃபைட்டு, C₆₀, CO/CO₂ மற்றும் காபனிக் அமிலம் பற்றி அறிக."],
 photos:["Diamond and graphite.jpg","Diamond and graphite comparison.png"],video:"J-SFzvYqhys",
 steps:[
 {t:["කාබන් බහුරූපී ආකාර","Carbon allotropes","காபனின் புறவேற்றுமை வடிவங்கள்"],d:["දියමන්ති sp³ ජාලයක් වන නිසා ඉතා දැඩිය. මිනිරන් sp² ස්තර සහ විස්ථානගත π ඉලෙක්ට්‍රෝන සහිත නිසා විදුලිය සන්නයනය කරයි; ස්තර පහසුවෙන් ලිස්සයි. C₆₀ යනු ගෝලාකාර fullerene ය.","Diamond has a rigid sp³ network; graphite consists of sp² sheets with delocalized π electrons and conducts electricity. C₆₀ is a spherical fullerene.","வைரம் வலுவான sp³ வலையமைப்பு. கிராஃபைட்டு sp² அடுக்குகளும் பரந்த π இலத்திரன்களும் கொண்ட மின்கடத்தி. C₆₀ கோள வடிவ fullerene."],eq:"දියමන්ති: sp³  |  මිනිරන්: sp²  |  C₆₀: fullerene"},
 {t:["කාබන් මොනොක්සයිඩ්","Carbon monoxide","காபன் மோனொக்சைடு"],d:["CO අවර්ණ, ගන්ධ රහිත හා ඉතා විෂ සහිත වායුවකි. C≡O බන්ධනය සහිත CO ලෝහ ඔක්සයිඩ ඔක්සිහරණයට යොදාගන්නා අතර ලිගන්ඩයක් ලෙස ද ක්‍රියා කරයි.","CO is colourless, odourless and highly poisonous. It has a strong C–O bond, can reduce metal oxides and can act as a ligand.","CO நிறமற்ற, மணமற்ற, மிகவும் நச்சு வாயு; உலோக ஒட்சைடுகளைக் குறைக்கும்; ஈந்தணுவாகவும் செயற்படும்."],eq:"Fe₂O₃ + 3CO → 2Fe + 3CO₂"},
 {t:["කාබන් ඩයොක්සයිඩ්","Carbon dioxide","காபன் டைஒக்சைடு"],d:["CO₂ අණුව රේඛීය O=C=O වේ. ඝන CO₂ (වියළි අයිස්) සාමාන්‍ය පීඩනයේදී ඌර්ධවපාතනය වේ. භෂ්ම සමඟ කාබනේට සහ අතිරික්ත CO₂ විට හයිඩ්‍රජන්කාබනේට සාදයි.","CO₂ is linear (O=C=O). Dry ice sublimes at normal pressure; reactions with alkalis form carbonate or hydrogen carbonate under excess CO₂.","CO₂ நேர்கோட்டு O=C=O. உலர் பனி உயர்பதனம் அடைகிறது. காரங்களுடன் கார்பனேட், அதிக CO₂ இல் ஐதரசன் கார்பனேட் கிடைக்கும்."],eq:"CO₂ + 2NaOH → Na₂CO₃ + H₂O"},
 {t:["කාබොනික් අම්ලය","Carbonic acid","காபனிக் அமிலம்"],d:["CO₂ ජලයේ දිය වූ විට කුඩා ප්‍රමාණයක් H₂CO₃ බවට පත් වේ. H₂CO₃ දුබල ද්විප්‍රෝටික අම්ලයකි; HCO₃⁻ හා CO₃²⁻ යන ආකාර සලකා බැලිය යුතුය.","Dissolved CO₂ establishes an equilibrium with H₂CO₃. Carbonic acid is weak and diprotic; distinguish HCO₃⁻ and CO₃²⁻.","நீரில் கரையும் CO₂, H₂CO₃ உடன் சமநிலை கொள்கிறது. இது வலுவற்ற இருபுரோட்டான் அமிலம்; HCO₃⁻, CO₃²⁻ முக்கியம்."],eq:"CO₂ + H₂O ⇌ H₂CO₃ ⇌ HCO₃⁻ + H⁺"}],
 qs:[
 ["මිනිරන් විදුලිය සන්නයනය කරන්නේ ඇයි?","Why does graphite conduct electricity?","கிராஃபைட்டு ஏன் மின்கடத்தி?",["sp³ නිසා","විස්ථානගත π e⁻ නිසා","H බන්ධන නිසා","අයන නිසා"],1,"මිනිරන්වල π ඉලෙක්ට්‍රෝන විස්ථානගත වී ඇත."],
 ["දියමන්ති කාබන් මුහුම්කරණය?","Hybridization of carbon in diamond?","வைரத்தில் C கலப்பினம்?",["sp","sp²","sp³","dsp²"],2,"දියමන්ති ත්‍රිමාන sp³ ජාලයකි."],
 ["CO₂ අණු හැඩය?","Molecular geometry of CO₂?","CO₂ மூலக்கூறு வடிவம்?",["වක්‍ර / bent","රේඛීය / linear","ත්‍රිකෝණාකාර / trigonal","චතුරස්‍ර / square"],1,"O=C=O රේඛීයය."],
 ["CO වායුව පිළිබඳ නිවැරදි කරුණ?","Correct fact about CO gas?","CO வாயு குறித்து சரியானது?",["විෂ රහිතයි","අතිශය විෂයි","කහ පාටයි","H₂ අඩංගුයි"],1,"CO ඉතා විෂ සහිත, අවර්ණ වායුවකි."],
 ["කාබොනික් අම්ලයේ සූත්‍රය?","Formula of carbonic acid?","காபனிக் அமில வாய்ப்பாடு?",["H₂CO₃","H₂SO₄","HClO₃","HNO₃"],0,"CO₂ හා ජලය අතර H₂CO₃ සමතුලිතය ඇත."]
 ]},
{ref:"4.5",pages:"139–145",name:["15 වන කාණ්ඩය — නයිට්‍රජන් හා ඇමෝනියා","Group 15 — nitrogen and ammonia","தொகுதி 15 — நைதரசன் மற்றும் அமோனியா"],
 intro:["නයිට්‍රජන්වල ඔක්සිකරණ අවස්ථා, නයිට්‍රික්/නයිට්‍රස් අම්ල, ඇමෝනියා හා ඇමෝනියම් ලවණ සහ ඒවා හඳුනාගැනීම අධ්‍යයනය කරන්න.","Study nitrogen oxidation states, nitric/nitrous acids, ammonia, ammonium salts and identification tests.","நைதரசன் ஒட்சியேற்ற நிலைகள், நைட்ரிக்/நைட்ரசு அமிலங்கள், அமோனியா, அமோனியம் உப்புகள் மற்றும் அடையாளச் சோதனைகளைப் படிக்கவும்."],
 photos:["Ammonia Fountain Experiment.jpg","Iodinecrystals.JPG"],video:"kJaqhpZVQdw",
 steps:[
 {t:["N₂ හි ස්ථායීතාව හා ඔක්සිකරණ අවස්ථා","N₂ stability and oxidation states","N₂ நிலைத்தன்மையும் ஒட்சியேற்ற நிலைகளும்"],d:["N≡N ප්‍රබල ත්‍රිත්ව බන්ධනය හේතුවෙන් N₂ සාමාන්‍ය තත්ත්වවලදී ස්ථායීය. N හි −3 (NH₃), +2 (NO), +4 (NO₂), +5 (HNO₃) ඇතුළු ඔක්සිකරණ අවස්ථා ඇත.","Strong N≡N bonding makes N₂ relatively inert. Nitrogen ranges from −3 in NH₃ to +5 in HNO₃.","வலுவான N≡N பிணைப்பால் N₂ நிலையானது. N இன் ஒட்சியேற்ற நிலைகள் NH₃ இல் −3 முதல் HNO₃ இல் +5 வரை."],eq:"NH₃: N −3  |  N₂: 0  |  NO: +2  |  NO₂: +4  |  HNO₃: +5"},
 {t:["නයිට්‍රික් හා නයිට්‍රස් අම්ල","Nitric and nitrous acids","நைட்ரிக் மற்றும் நைட்ரசு அமிலங்கள்"],d:["HNO₂ දුබල, අස්ථායී අම්ලයකි; HNO₃ ප්‍රබල ඔක්සිකාරකයකි. තනුක HNO₃ සමඟ Cu ප්‍රධාන වශයෙන් NO ද, සාන්ද්‍ර HNO₃ සමඟ NO₂ ද නිකුත් කරයි.","HNO₂ is weak and unstable; HNO₃ is a strong oxidizing agent. Copper gives NO with dilute nitric acid and NO₂ with concentrated acid.","HNO₂ வலுவற்ற, நிலையற்ற அமிலம்; HNO₃ வலுவான ஒட்சியேற்றி. Cu தளர்ந்த அமிலத்துடன் NO, செறிந்த அமிலத்துடன் NO₂ தரும்."],eq:"3Cu + 8HNO₃(dil) → 3Cu(NO₃)₂ + 2NO + 4H₂O"},
 {t:["ඇමෝනියා හා ඇමෝනියම්","Ammonia and ammonium","அமோனியா மற்றும் அமோனியம்"],d:["NH₃ ජලයේ දිය වී දුබල භෂ්මයක් ලෙස ක්‍රියා කරයි. NH₄⁺ අඩංගු ලවණ NaOH සමඟ උණු කළ විට NH₃ නිකුත් වේ; HCl වාෂ්ප සමඟ සුදු NH₄Cl දුමක් ලබා දෙයි.","NH₃ is a weak base in water. Warm ammonium salts with alkali to release NH₃, identified by white NH₄Cl fumes with HCl.","NH₃ நீரில் வலுவற்ற காரம். அமோனியம் உப்புகளை காரத்துடன் சூடாக்க NH₃ வெளியேறும்; HCl உடன் வெள்ளை NH₄Cl புகை."],eq:"NH₄⁺ + OH⁻ → NH₃ + H₂O  |  NH₃ + HCl → NH₄Cl"},
 {t:["නයිට්‍රේට් හඳුනාගැනීම","Testing for nitrate","நைட்ரேட் அடையாளச் சோதனை"],d:["Fe²⁺ සහ සාන්ද්‍ර H₂SO₄ භාවිතයෙන් නයිට්‍රේට් සඳහා දුඹුරු වළලු පරීක්ෂාව කරයි; [Fe(NO)]²⁺ සංකීර්ණය වර්ණයට හේතුවයි. මෙය අධීක්ෂණය යටතේ පමණක් සිදු කරන පරීක්ෂාවකි.","The brown-ring test for nitrate involves Fe²⁺, concentrated H₂SO₄ and a coloured [Fe(NO)]²⁺ complex. Laboratory supervision is essential.","Fe²⁺, செறிந்த H₂SO₄ மூலம் நைட்ரேட்டிற்கு பழுப்பு வளையச் சோதனை; [Fe(NO)]²⁺ நிறத்திற்குக் காரணம். ஆய்வக மேற்பார்வை அவசியம்."],eq:"Fe²⁺ + NO → [Fe(NO)]²⁺"}],
 qs:[
 ["NH₃ හි N ඔක්සිකරණ අංකය?","Oxidation number of N in NH₃?","NH₃ இல் N இன் ஒட்சியேற்ற எண்?",["−3","0","+3","+5"],0,"H +1 බැවින් N −3 වේ."],
 ["සාන්ද්‍ර HNO₃ සමඟ Cu දෙන දුඹුරු වායුව?","Brown gas from Cu + concentrated HNO₃?","செறிந்த HNO₃ + Cu இல் பழுப்பு வாயு?",["NO","NO₂","NH₃","N₂"],1,"NO₂ රතු-දුඹුරු වායුවකි."],
 ["ඇමෝනියම් ලවණ NaOH සමඟ රත් කළ විට?","Heating ammonium salt with NaOH yields?","அமோனியம் உப்பை NaOH உடன் சூடாக்கினால்?",["H₂","O₂","NH₃","Cl₂"],2,"NH₄⁺ + OH⁻ → NH₃ + H₂O."],
 ["දුඹුරු වළලු පරීක්ෂාවෙන් හඳුනාගන්නේ?","Brown-ring test identifies?","பழுப்பு வளையச் சோதனை கண்டறிவது?",["SO₄²⁻","NO₃⁻","Cl⁻","CO₃²⁻"],1,"නයිට්‍රේට් හඳුනාගැනීම සඳහා යොදයි."],
 ["NH₃ හා HCl වායු හමුවේ නිපදෙන්නේ?","NH₃ + HCl gases form?","NH₃ + HCl வாயுக்கள் உருவாக்குவது?",["NH₄Cl","NCl₃","NO₂","HNO₃"],0,"සුදු NH₄Cl දුමක් සෑදේ."]
 ]},
{ref:"4.6",pages:"145–153",name:["16 වන කාණ්ඩය — ඔක්සිජන් හා සල්ෆර්","Group 16 — oxygen and sulfur","தொகுதி 16 — ஒட்சிசன் மற்றும் கந்தகம்"],
 intro:["O₂/O₃, H₂O/H₂O₂, සල්ෆර් බහුරූපීතාව, H₂S, SO₂, H₂SO₃ හා H₂SO₄ පිළිබඳ NIE අන්තර්ගතය සම්බන්ධ කරගන්න.","Connect O₂/O₃, H₂O/H₂O₂, sulfur allotropy, H₂S, SO₂, H₂SO₃ and H₂SO₄.","O₂/O₃, H₂O/H₂O₂, கந்தகப் புறவேற்றுமை, H₂S, SO₂, H₂SO₃, H₂SO₄ ஆகியவற்றை இணைத்துப் படிக்கவும்."],
 photos:["Sulfur crystals.jpg","Sulfur crystals.jpg"],video:"Ad7Y4LZ65Y0",
 steps:[
 {t:["ඔක්සිජන් හා ඕසෝන්","Oxygen and ozone","ஒட்சிசனும் ஓசோனும்"],d:["O₂ සහ O₃ එකම මූලද්‍රව්‍යයේ බහුරූපී ආකාර දෙකකි. ඕසෝන් O₂ ට වඩා ප්‍රබල ඔක්සිකාරකයකි. O₂, H₂O₂ උත්ප්‍රේරිත වියෝජනයෙන් ලබාගත හැක.","O₂ and O₃ are allotropes; ozone is generally a stronger oxidizer. Catalytic decomposition of H₂O₂ produces O₂.","O₂, O₃ புறவேற்றுமை வடிவங்கள்; ஓசோன் வலுவான ஒட்சியேற்றி. H₂O₂ சிதைவில் O₂ பெறலாம்."],eq:"2H₂O₂ → 2H₂O + O₂"},
 {t:["සල්ෆර් බහුරූපීතාව","Sulfur allotropy","கந்தகப் புறவேற்றுமை"],d:["රොම්බීය α-S₈ හා ඒකානතික β-S₈ සල්ෆර් අණු අටක වළලු සහිත ස්ඵටික ආකාර දෙකකි. උණු කොට ඉක්මනින් සිසිල් කළ විට සුනම්‍ය සල්ෆර් සෑදිය හැක.","Rhombic α-S₈ and monoclinic β-S₈ contain cyclic S₈ rings but have different packing. Rapid cooling of molten sulfur yields plastic sulfur.","ரோம்பிக் α-S₈ மற்றும் ஒற்றைச்சாய்வு β-S₈ ஆகியவற்றில் S₈ வளையங்கள் உள்ளன; உருகிய கந்தகத்தை வேகமாகக் குளிர்வித்தால் நெகிழ் கந்தகம் கிடைக்கும்."],eq:"α-S₈ ⇄ β-S₈ (උෂ්ණත්වය අනුව)"},
 {t:["හයිඩ්‍රජන් පෙරොක්සයිඩ්","Hydrogen peroxide","ஐதரசன் பெரொட்சைடு"],d:["H₂O₂ තුළ O හි ඔක්සිකරණ අංකය −1 ය. H₂O₂ ඔක්සිකාරකයක් ලෙස I⁻ → I₂ ද, ඔක්සිහාරකයක් ලෙස MnO₄⁻ → Mn²⁺ ද ක්‍රියා කළ හැක. එය අස්ථායී නිසා වියෝජනය වෙයි.","O is −1 in H₂O₂; it may oxidize I⁻ to I₂ or reduce permanganate to Mn²⁺ in acid. H₂O₂ decomposes readily.","H₂O₂ இல் O = −1. இது I⁻ ஐ I₂ ஆக ஒட்சியேற்றவும் அமில MnO₄⁻ ஐ Mn²⁺ ஆகக் குறைக்கவும் முடியும்."],eq:"H₂O₂ + 2H⁺ + 2I⁻ → I₂ + 2H₂O"},
 {t:["H₂S, SO₂ හා සල්ෆර් ඔක්සෝ අම්ල","Sulfur compounds and oxoacids","கந்தகச் சேர்வுகளும் ஒக்சோ அமிலங்களும்"],d:["H₂S විෂ සහිත දුබල අම්ලයක් හා ඔක්සිහාරකයකි. SO₂ බොහෝවිට ඔක්සිහාරකයක් ලෙස ක්‍රියා කරයි. සාන්ද්‍ර H₂SO₄ ප්‍රබල අම්ලයක්, විජලකාරකයක් සහ උණු තත්ත්වයේ ඔක්සිකාරකයක් වේ.","H₂S is toxic, weakly acidic and reducing. SO₂ often acts as a reducing agent. Concentrated H₂SO₄ acts as an acid, dehydrating agent and, when hot, an oxidizer.","H₂S நச்சான வலுவற்ற அமிலமும் குறைப்பானும். SO₂ பொதுவாக குறைப்பான். செறிந்த H₂SO₄ அமிலம், நீர்நீக்கி, சூடாக ஒட்சியேற்றி."],eq:"SO₃ + H₂O → H₂SO₄  |  2H₂S + SO₂ → 3S + 2H₂O"}],
 qs:[
 ["H₂O₂ තුළ O ඔක්සිකරණ අංකය?","Oxidation state of O in H₂O₂?","H₂O₂ இல் O இன் ஒட்சியேற்ற எண்?",["−2","−1","0","+1"],1,"පෙරොක්සයිඩවල O = −1."],
 ["O₂ හා O₃ සම්බන්ධතාව?","O₂ and O₃ are?","O₂ மற்றும் O₃ என்ன?",["සමස්ථානික / isotopes","බහුරූපී / allotropes","අයන / ions","සමාවයවික / isomers"],1,"O₂ හා O₃ එකම මූලද්‍රව්‍යයේ බහුරූපීය."],
 ["බහුල සල්ෆර් ස්ඵටික වළල්ල?","Common cyclic sulfur molecule?","பொதுவான கந்தக வளையம்?",["S₂","S₄","S₈","S₁₂"],2,"α හා β සල්ෆර් දෙකම S₈ වළලු ඇත."],
 ["H₂S සහ SO₂ වල ප්‍රතික්‍රියා ඵලය?","Product of H₂S + SO₂ reaction?","H₂S + SO₂ தாக்க விளைவு?",["S","H₂","Cl₂","NH₃"],0,"2H₂S + SO₂ → 3S + 2H₂O."],
 ["SO₃ ජලය සමඟ සෑදෙන්නේ?","SO₃ + water forms?","SO₃ + நீர் உருவாக்குவது?",["H₂SO₃","H₂SO₄","H₂S","SO₂"],1,"SO₃ + H₂O → H₂SO₄."]
 ]},
{ref:"4.7",pages:"153–157",name:["17 වන කාණ්ඩය — හේලජන","Group 17 — halogens","தொகுதி 17 — அலசன்கள்"],
 intro:["F, Cl, Br, I හි ඔක්සිකාරක බලය, හයිඩ්‍රජන් හේලයිඩ, AgNO₃ පරීක්ෂාව, ක්ලෝරීන්හි විෂමයෝජනය හා ඔක්සෝ අම්ල අධ්‍යයනය කරන්න.","Study halogen oxidizing power, hydrogen halides, silver-halide tests, chlorine disproportionation and oxoacids.","அலசன் ஒட்சியேற்ற வலிமை, ஐதரசன் அலசைடுகள், வெள்ளி சோதனை, குளோரின் இருவழிமாற்றம் மற்றும் ஒக்சோ அமிலங்கள்."],
 photos:["Iodinecrystals.JPG","Flammenfärbung Kalium (K).jpg"],video:"QH3QKQCZ11I",
 steps:[
 {t:["ප්‍රතික්‍රියාශීලීතාව හා විස්ථාපනය","Halogen reactivity and displacement","அலசன் தாக்கத்திறனும் இடப்பெயர்ச்சியும்"],d:["හැලජනවල ඔක්සිකාරක බලය F₂ සිට I₂ දක්වා සාමාන්‍යයෙන් අඩු වේ. Cl₂ ට Br⁻, I⁻ ඔක්සිකරණය කළ හැක; Br₂ ට I⁻ ඔක්සිකරණය කළ හැක.","Oxidizing power generally decreases F₂ → I₂. Cl₂ displaces bromide and iodide, while Br₂ displaces iodide.","F₂ முதல் I₂ வரை ஒட்சியேற்ற வலிமை குறையும். Cl₂, Br⁻ மற்றும் I⁻ ஐ; Br₂, I⁻ ஐ இடம்பெயர்க்கும்."],eq:"Cl₂ + 2Br⁻ → 2Cl⁻ + Br₂"},
 {t:["හයිඩ්‍රජන් හේලයිඩවල ආම්ලිකතාව","Hydrogen-halide acidity","ஐதரசன் அலசைடுகளின் அமிலத் தன்மை"],d:["ජලීය HF දුබල අම්ලයකි; HCl, HBr, HI ප්‍රබල අම්ල වේ. HX බන්ධන ශක්තිය පහළට අඩු වන බැවින් ආම්ලික බලය වැඩි වේ.","HF is a weak aqueous acid; HCl, HBr and HI are strong. H–X bond dissociation becomes easier down the group.","HF நீரில் வலுவற்ற அமிலம்; HCl, HBr, HI வலுவானவை. கீழே செல்ல H–X பிணைப்பு பலவீனமடைகிறது."],eq:"HF < HCl < HBr < HI : ආම්ලික බලය"},
 {t:["රිදී නයිට්‍රේට් හඳුනාගැනීම","Silver nitrate identification","வெள்ளி நைட்ரேட் அடையாளம்"],d:["AgCl සුදු හා තනුක NH₃ තුළ ද්‍රාව්‍යය. AgBr ලා කහ හා සාන්ද්‍ර NH₃ තුළ ද්‍රාව්‍යය. AgI කහ හා සාමාන්‍ය ඇමෝනියා ද්‍රාවණවල අද්‍රාව්‍යය. අදාළ අයන හඳුනාගැනීමට මෙම රටාව උපකාරී වේ.","AgCl: white, soluble in dilute NH₃; AgBr: cream, soluble in concentrated NH₃; AgI: yellow, insoluble in either.","AgCl வெள்ளை, தளர்ந்த NH₃ இல் கரையும்; AgBr வெளிர்மஞ்சள், செறிந்த NH₃ இல் கரையும்; AgI மஞ்சள், இரண்டிலும் கரையாது."],eq:"Ag⁺ + X⁻ → AgX(s)  |  AgCl: සුදු  •  AgBr: ලා කහ  •  AgI: කහ"},
 {t:["ක්ලෝරීන් හා ඔක්සෝ අම්ල","Chlorine and oxoacids","குளோரினும் ஒக்சோ அமிலங்களும்"],d:["Cl₂ ජලය හෝ ශීත තනුක NaOH සමඟ ක්‍රියා කරන විට Cl ඔක්සිකරණයත් ඔක්සිහරණයත් වේ. ක්ලෝරීන් ඔක්සෝ අම්ලවල ආම්ලික බලය HOCl සිට HClO₄ දක්වා වැඩි වේ.","Cl₂ disproportionates in water or cold dilute alkali. Chlorine oxoacid acidity increases from HOCl to HClO₄.","Cl₂ நீர், குளிர்ந்த தளர்ந்த NaOH உடன் இருவழிமாற்றம் அடையும். HOCl முதல் HClO₄ வரை அமில வலிமை அதிகரிக்கிறது."],eq:"Cl₂ + 2NaOH(cold) → NaCl + NaOCl + H₂O"}],
 qs:[
 ["Cl₂ ට විස්ථාපනය කළ හැක්කේ?","Which ion can Cl₂ displace?","Cl₂ இடம்பெயர்க்கும் அயன்?",["F⁻","Br⁻","Ne","Ar"],1,"Cl₂, Br⁻ → Br₂ ඔක්සිකරණය කරයි."],
 ["දුබල ජලීය හයිඩ්‍රජන් හේලයිඩ අම්ලය?","Weak aqueous hydrogen halide acid?","வலுவற்ற நீர்க்கரைசல் HX அமிலம்?",["HF","HCl","HBr","HI"],0,"HF හි H–F බන්ධනය ප්‍රබලය."],
 ["සුදු AgX අවක්ෂේපය?","White silver-halide precipitate?","வெள்ளை வெள்ளி அலசைடு வீழ்படிவு?",["AgI","AgBr","AgCl","AgF"],2,"AgCl සුදු අවක්ෂේපයකි."],
 ["AgI ඇමෝනියා සමඟ?","AgI in aqueous ammonia?","NH₃ கரைசலில் AgI?",["තනුකයේ දියවේ","සාන්ද්‍රයේ දියවේ","සාමාන්‍යයෙන් නොදියවේ","වායුවක් නිපදේ"],2,"AgI NH₃ ද්‍රාවණවල නොදියවේ."],
 ["ප්‍රබලතම ක්ලෝරීන් ඔක්සෝ අම්ලය?","Strongest chlorine oxoacid listed?","மிக வலுவான குளோரின் ஒக்சோ அமிலம்?",["HOCl","HClO₂","HClO₃","HClO₄"],3,"ඔක්සිකරණ අංකය +7 දක්වා වැඩි වන විට ආම්ලික බලය වැඩි වේ."]
 ]},
{ref:"4.8",pages:"157–159",name:["18 වන කාණ්ඩය — උච්ච වායු","Group 18 — noble gases","தொகுதி 18 — உயர்குல வாயுக்கள்"],
 intro:["බාහිර කවචය සම්පූර්ණ උච්ච වායු බොහෝවිට අක්‍රිය වුවද Xe ෆ්ලෝරයිඩ හා ඔක්සයිඩ නිපදවන්නේ ඇයිදැයි සොයා බලන්න.","Learn why noble gases are usually inert and why xenon forms fluorides and oxides.","நிறைந்த வெளிக்கூடு கொண்ட உயர் வாயுக்கள் பொதுவாக மந்தமாக இருந்தாலும் Xe ஏன் சேர்வுகளை உருவாக்குகிறது என அறிக."],
 photos:["Xenonlamp.jpg","Xenon light.jpg"],video:"",
 steps:[
 {t:["උච්ච වායුවල වින්‍යාසය","Noble-gas configuration","உயர் வாயுக்களின் அமைப்பு"],d:["He හි 1s² සහ අනෙක් උච්ච වායුවල ns²np⁶ වින්‍යාසය බාහිර කවචය සම්පූර්ණ කරයි. සාමාන්‍යයෙන් ඒවා ඒකපරමාණුක හා අඩු ප්‍රතික්‍රියාශීලීය.","He has 1s²; the others are ns²np⁶. Filled valence shells make noble gases monatomic and usually unreactive.","He இல் 1s²; மற்றவற்றில் ns²np⁶. நிறைந்த வெளிக்கூட்டால் தனி அணு வாயுக்களாகவும் மந்தமாகவும் உள்ளன."],eq:"He: 1s²  |  Ne–Xe: ns²np⁶"},
 {t:["අයනීකරණ ශක්ති ප්‍රවණතාව","Ionization-energy trend","அயனியாக்க ஆற்றல் போக்கு"],d:["කාණ්ඩය පහළට පරමාණුක ප්‍රමාණය වැඩි වන අතර අයනීකරණ ශක්තිය අඩු වේ. Xe හි ඉලෙක්ට්‍රෝන ඉවත් කිරීම He/Ne ට වඩා පහසුය.","Ionization energy decreases down Group 18, making the heavier members comparatively more reactive.","தொகுதி 18 கீழே செல்ல அயனியாக்க ஆற்றல் குறைவதால் கனமான உறுப்பினர்கள் ஒப்பீட்டளவில் அதிக வினைத்திறன் பெறுகின்றன."],eq:"He > Ne > Ar > Kr > Xe : 1 වන අයනීකරණ ශක්තිය"},
 {t:["සීනෝන් ෆ්ලෝරයිඩ","Xenon fluorides","செனான் புளோரைடுகள்"],d:["සුදුසු තත්ත්වවලදී XeF₂, XeF₄, XeF₆ සෑදේ. XeF₂ රේඛීය, XeF₄ චතුරස්‍ර තලීය, XeF₆ විකෘති අෂ්ටතලීය ලෙස විස්තර කරයි.","Xe forms XeF₂ (linear), XeF₄ (square planar) and XeF₆ (distorted octahedral).","XeF₂ நேர்கோட்டு, XeF₄ சதுரத் தள, XeF₆ சீரற்ற எண்முகி வடிவம் கொண்டவை."],eq:"XeF₂: +2  |  XeF₄: +4  |  XeF₆: +6"},
 {t:["සීනෝන් ඔක්සයිඩ","Xenon oxides","செனான் ஒட்சைடுகள்"],d:["XeO₃ හි Xe +6 හා XeO₄ හි +8 ඔක්සිකරණ අවස්ථා දරයි. Xe සංයෝග අස්ථායී විය හැකි බැවින් මෙය සංකල්පමය අධ්‍යයනයට පමණි.","XeO₃ contains Xe(+6), XeO₄ contains Xe(+8); many xenon compounds are unstable and require specialist handling.","XeO₃ இல் Xe +6; XeO₄ இல் +8. பல சேர்வுகள் நிலையற்றவை; இது கோட்பாட்டு ஆய்வு மட்டுமே."],eq:"XeO₃: Xe +6  |  XeO₄: Xe +8"}],
 qs:[
 ["He බාහිර වින්‍යාසය?","He configuration?","He அமைப்பு?",["1s¹","1s²","2s²2p⁶","3s²"],1,"He යනු 1s²."],
 ["XeF₄ හැඩය?","Shape of XeF₄?","XeF₄ வடிவம்?",["රේඛීය / linear","චතුරස්‍ර තලීය / square planar","ත්‍රිකෝණාකාර / trigonal","චතුස්තලීය / tetrahedral"],1,"XeF₄ චතුරස්‍ර තලීය වේ."],
 ["XeF₂ හැඩය?","Shape of XeF₂?","XeF₂ வடிவம்?",["රේඛීය / linear","වක්‍ර / bent","චතුස්තලීය / tetrahedral","ත්‍රිකෝණාකාර / trigonal"],0,"XeF₂ රේඛීය වේ."],
 ["XeO₄ හි Xe ඔක්සිකරණ අංකය?","Oxidation state Xe in XeO₄?","XeO₄ இல் Xe ஒட்சியேற்ற நிலை?",["+2","+4","+6","+8"],3,"O හතරක් −8; Xe +8."],
 ["උච්ච වායු සාමාන්‍යයෙන් පවතින්නේ?","Noble gases generally occur as?","உயர் வாயுக்கள் பொதுவாக இருப்பது?",["දිවිපරමාණුක","ඒකපරමාණුක","දැල් සහසංයුජ","අයනික ඝන"],1,"ඒවා ඒකපරමාණුක වායු වේ."]
 ]},
{ref:"4.9",pages:"159–163",name:["3 වන ආවර්තය — ආවර්තිතා රටා","Period 3 — periodic trends","மூன்றாம் ஆவர்த்தனம் — போக்குகள்"],
 intro:["Na සිට Ar දක්වා ලෝහක ගුණ, ඔක්සයිඩවල ආම්ලික/භාෂ්මික ස්වභාවය, හයිඩ්‍රොක්සයිඩ, හයිඩ්‍රයිඩ හා ක්ලෝරයිඩ සසඳන්න.","Compare metallic character, oxides, hydroxides, hydrides and chlorides across Na to Ar.","Na முதல் Ar வரை உலோகப் பண்பு, ஒட்சைடுகள், ஐதரொட்சைடுகள், ஐதரைடுகள், குளோரைடுகளை ஒப்பிடுக."],
 photos:["Alternative periodic table with orbital energy levels.jpg","Diamond and graphite.png"],video:"",
 steps:[
 {t:["ඉලෙක්ට්‍රෝන වින්‍යාසය සහ ලෝහක ගුණ","Configurations and metallic character","இலத்திரன் அமைப்பும் உலோகப் பண்பும்"],d:["Na, Mg, Al, Si, P, S, Cl, Ar මඟින් ns¹ සිට ns²np⁶ දක්වා වින්‍යාසය විකාශනය වේ. වමේ සිට දකුණට සාමාන්‍යයෙන් ලෝහක ගුණ අඩු වේ.","Across Na–Ar the valence configuration progresses ns¹ to ns²np⁶ and metallic character generally falls.","Na–Ar வரிசையில் ns¹ முதல் ns²np⁶ வரை மாறும்; இடமிருந்து வலமாக உலோகப் பண்பு குறையும்."],eq:"Na → Mg → Al → Si → P → S → Cl → Ar"},
 {t:["ඔක්සයිඩවල ස්වභාවය","Nature of oxides","ஒட்சைடுகளின் இயல்பு"],d:["Na₂O හා MgO භාෂ්මික, Al₂O₃ උභයගුණී, SiO₂ දුබල ආම්ලික, P₄O₁₀/SO₃/Cl₂O₇ ආම්ලික ඔක්සයිඩ වේ. වමේ සිට දකුණට ආම්ලික ස්වභාවය වැඩි වේ.","Na₂O and MgO are basic, Al₂O₃ amphoteric, SiO₂ weakly acidic and later nonmetal oxides acidic.","Na₂O, MgO கார; Al₂O₃ இருபண்பு; SiO₂ வலுவற்ற அமில; P₄O₁₀, SO₃, Cl₂O₇ அமில ஒட்சைடுகள்."],eq:"Na₂O → MgO → Al₂O₃ → SiO₂ → P₄O₁₀ → SO₃ → Cl₂O₇"},
 {t:["හයිඩ්‍රොක්සයිඩ හා හයිඩ්‍රයිඩ","Hydroxides and hydrides","ஐதரொட்சைடுகளும் ஐதரைடுகளும்"],d:["NaOH ප්‍රබල භාෂ්මයක්, Mg(OH)₂ භාෂ්මික, Al(OH)₃ උභයගුණීය. PH₃ ඉතා දුබල භාෂ්මයකි; H₂S දුබල අම්ලයක් වන අතර HCl ජලයේ ප්‍රබල අම්ලයකි.","NaOH is strongly basic, Mg(OH)₂ basic, Al(OH)₃ amphoteric. PH₃ is very weakly basic, H₂S weakly acidic, HCl strongly acidic in water.","NaOH வலுவான காரம்; Mg(OH)₂ காரம்; Al(OH)₃ இருபண்பு; PH₃ மிக வலுவற்ற காரம்; H₂S வலுவற்ற அமிலம்; HCl வலுவான அமிலம்."],eq:"NaOH (භෂ්ම) → Al(OH)₃ (උභයගුණී) → HCl(aq) (අම්ල)"},
 {t:["ක්ලෝරයිඩවල ජලවිච්ඡේදනය","Chloride hydrolysis","குளோரைடு நீராற்பகுப்பு"],d:["NaCl වැනි අයනික ක්ලෝරයිඩ සාමාන්‍යයෙන් ජලවිච්ඡේදනය නොවෙයි. AlCl₃, SiCl₄, PCl₅ වැනි සහසංයුජ ස්වභාවයක් සහිත ක්ලෝරයිඩ ජලය සමඟ ආම්ලික ඵල දෙයි.","Ionic NaCl does not hydrolyse appreciably; covalent chlorides such as SiCl₄ and PCl₅ react with water producing acidic products.","NaCl போன்ற அயனிக் குளோரைடு நீராற்பகுப்படையாது; SiCl₄, PCl₅ நீருடன் தாக்கி அமில விளைவுகளைத் தரும்."],eq:"SiCl₄ + 2H₂O → SiO₂ + 4HCl  |  PCl₅ + 4H₂O → H₃PO₄ + 5HCl"}],
 qs:[
 ["3 ආවර්තයේ උභයගුණී ඔක්සයිඩය?","Amphoteric Period 3 oxide?","3 ஆம் ஆவர்த்தன இருபண்பு ஒட்சைடு?",["Na₂O","Al₂O₃","SO₃","Cl₂O₇"],1,"Al₂O₃ උභයගුණී වේ."],
 ["වමේ සිට දකුණට ඔක්සයිඩවල ආම්ලිකතාව?","Oxide acidity left to right?","ஒட்சைடு அமிலத் தன்மை இடம்→வலம்?",["වැඩිවේ / increases","අඩුවේ / decreases","නොවෙනස් / unchanged","ශූන්‍ය වේ"],0,"ලෝහක ගුණ අඩුවීමත් සමඟ ආම්ලික බව වැඩිවේ."],
 ["ජලය සමඟ HCl නිපදවන ක්ලෝරයිඩය?","Chloride producing HCl on hydrolysis?","நீருடன் HCl உருவாக்கும் குளோரைடு?",["NaCl","SiCl₄","KCl","CaCl₂"],1,"SiCl₄ + 2H₂O → SiO₂ + 4HCl."],
 ["උභයගුණී හයිඩ්‍රොක්සයිඩය?","Amphoteric hydroxide?","இருபண்புடைய ஐதரொட்சைடு?",["NaOH","Mg(OH)₂","Al(OH)₃","HCl"],2,"Al(OH)₃ අම්ල හා භෂ්ම දෙක සමඟ ක්‍රියා කරයි."],
 ["3 ආවර්තය අවසානයේ තිබෙන්නේ?","Element at end of Period 3?","3 ஆம் ஆவர்த்தன முடிவு தனிமம்?",["Na","Si","Cl","Ar"],3,"3 ආවර්තය Ar වලින් අවසන් වේ."]
 ]},
{ref:"4.10",pages:"163–179",name:["d ගොනුව — ආන්තරික මූලද්‍රව්‍ය","d-block — transition elements","d கட்டம் — இடைநிலைத் தனிமங்கள்"],
 intro:["Sc–Zn, විචල්‍ය ඔක්සිකරණ අංක, Cr/Mn ඔක්සෝ අයන, සංකීර්ණ අයන, ලිගන්ඩ් නාමකරණය, වර්ණ සහ කැටායන හඳුනාගැනීම එකට සම්බන්ධ කරන්න.","Explore Sc–Zn, variable oxidation states, Cr/Mn oxoanions, complex ions, ligands, colours and cation tests.","Sc–Zn, மாறும் ஒட்சியேற்ற நிலைகள், Cr/Mn ஒக்சோ அயன்கள், அணைவுச் சேர்மங்கள், நிறங்கள் மற்றும் அயன் சோதனைகளைப் படிக்கவும்."],
 photos:["Potassium permanganate crystals.jpg","Potassium Permanganate.jpg"],video:"",
 steps:[
 {t:["ආන්තරික මූලද්‍රව්‍ය හා ඔක්සිකරණ අවස්ථා","Transition elements and oxidation states","இடைநிலைத் தனிமங்களும் ஒட்சியேற்ற நிலைகளும்"],d:["d ගොනුවේ සියලු මූලද්‍රව්‍ය ආන්තරික නොවේ; Zn හා Zn²⁺ හි d¹⁰ නිසා Zn ආන්තරික නොවේ. Fe හි +2,+3; Cu හි +1,+2; Mn හි +2,+4,+7 වැනි වෙනස් අවස්ථා දැකිය හැක.","Not every d-block element is a transition element: Zn and Zn²⁺ have d¹⁰. Fe, Cu and Mn exhibit variable oxidation states.","அனைத்து d கட்டத் தனிமங்களும் இடைநிலை அல்ல; Zn, Zn²⁺ இல் d¹⁰. Fe, Cu, Mn மாறும் ஒட்சியேற்ற நிலைகளை காட்டுகின்றன."],eq:"Fe: +2,+3  |  Cu: +1,+2  |  Mn: +2,+4,+7"},
 {t:["ක්‍රෝමේට් හා ඩයික්‍රෝමේට්","Chromate and dichromate","குரோமேட்டு மற்றும் இருகுரோமேட்டு"],d:["CrO₄²⁻ කහ පැහැති අතර Cr₂O₇²⁻ තැඹිලි වේ. ආම්ලික මාධ්‍යයේ ඩයික්‍රෝමේට් පැත්තට ද, භාෂ්මික මාධ්‍යයේ ක්‍රෝමේට් පැත්තට ද සමතුලිතතාව ගමන් කරයි.","Chromate CrO₄²⁻ is yellow; dichromate Cr₂O₇²⁻ is orange. Acid favours dichromate; alkali favours chromate.","CrO₄²⁻ மஞ்சள்; Cr₂O₇²⁻ செம்மஞ்சள். அமிலத்தில் இருகுரோமேட்டு, காரத்தில் குரோமேட்டு மேலோங்கும்."],eq:"2CrO₄²⁻ + 2H⁺ ⇌ Cr₂O₇²⁻ + H₂O"},
 {t:["මැංගනේට්, පෙර්මැංගනේට් හා ඔක්සිකරණය","Manganate and permanganate","மாங்கனேட்டு மற்றும் பெர்மாங்கனேட்டு"],d:["MnO₄²⁻ කොළ, MnO₄⁻ තද දම් පැහැති වේ. ආම්ලික මාධ්‍යයේ MnO₄⁻ ඔක්සිකාරකයක් ලෙස Mn²⁺ බවට පත් වෙයි. වර්ණ වෙනස සහ ඔක්සිකරණ අංක දෙකම සම්බන්ධ කරන්න.","MnO₄²⁻ is green and MnO₄⁻ purple. In acidic conditions MnO₄⁻ can be reduced to Mn²⁺ while oxidizing a reductant.","MnO₄²⁻ பச்சை, MnO₄⁻ ஊதா. அமில நிலையில் MnO₄⁻, Mn²⁺ ஆகக் குறைகிறது."],eq:"MnO₄⁻ + 8H⁺ + 5e⁻ → Mn²⁺ + 4H₂O"},
 {t:["ලිගන්ඩ්, වර්ණ හා හඳුනාගැනීම","Ligands, colours and identification","ஈந்தணுக்கள், நிறங்கள், அடையாளச் சோதனைகள்"],d:["H₂O, NH₃, Cl⁻ වැනි ලිගන්ඩ් මධ්‍යම ලෝහ අයනයට ඉලෙක්ට්‍රෝන යුගල ලබා දෙයි. Cu²⁺ ජලීය ද්‍රාවණය නිල්; අතිරික්ත NH₃ සමඟ තද නිල් [Cu(NH₃)₄]²⁺ සංකීර්ණය සෑදේ. Fe³⁺ + SCN⁻ රතු සංකීර්ණයක් ලබා දෙයි.","Ligands donate electron pairs. Aqueous Cu²⁺ is blue and forms deep-blue [Cu(NH₃)₄]²⁺ with excess ammonia. Fe³⁺/SCN⁻ gives a red complex.","H₂O, NH₃, Cl⁻ இலத்திரன் இரட்டையை வழங்கும் ஈந்தணுக்கள். Cu²⁺ நீலம்; அதிக NH₃ இல் ஆழ்நீல [Cu(NH₃)₄]²⁺ உருவாகும். Fe³⁺, SCN⁻ உடன் சிவப்பு அணைவு."],eq:"[Cu(H₂O)₆]²⁺ + 4NH₃ ⇌ [Cu(NH₃)₄(H₂O)₂]²⁺ + 4H₂O"}],
 qs:[
 ["Zn ආන්තරික නොවීමට ප්‍රධාන හේතුව?","Why is Zn not a transition element?","Zn ஏன் இடைநிலைத் தனிமம் அல்ல?",["d⁰ පමණි","d¹⁰ වින්‍යාසය","+7 අංකය","වායුමය නිසා"],1,"Zn සහ Zn²⁺ හි d¹⁰ වේ."],
 ["Cr₂O₇²⁻ වර්ණය?","Dichromate colour?","Cr₂O₇²⁻ நிறம்?",["කහ / yellow","තැඹිලි / orange","කොළ / green","නිල් / blue"],1,"ඩයික්‍රෝමේට් තැඹිලි; ක්‍රෝමේට් කහ."],
 ["MnO₄⁻ වර්ණය?","Permanganate colour?","MnO₄⁻ நிறம்?",["දම් / purple","කොළ / green","කහ / yellow","සුදු / white"],0,"පෙර්මැංගනේට් දම් පැහැති වේ."],
 ["අතිරික්ත NH₃ සමඟ Cu²⁺ ද්‍රාවණය?","Cu²⁺ with excess ammonia becomes?","அதிக NH₃ உடன் Cu²⁺ கரைசல்?",["තද නිල් / deep blue","අවර්ණ / colourless","තද රතු / crimson","කහ / yellow"],0,"[Cu(NH₃)₄]²⁺ තද නිල් වර්ණය පෙන්වයි."],
 ["Fe³⁺ හා SCN⁻ වල ලක්ෂණික පැහැය?","Fe³⁺ + SCN⁻ complex colour?","Fe³⁺ + SCN⁻ அணைவு நிறம்?",["කොළ / green","රතු / red","නිල් / blue","සුදු / white"],1,"Fe³⁺ සහ SCN⁻ මඟින් රතු සංකීර්ණයක් සාදයි."]
 ]}
];
window.U6_STRUCTURED=[
["1 වන කාණ්ඩයේ Na සහ K ජලය හා O₂ සමඟ දක්වන ප්‍රතික්‍රියා සංසන්දනය කර තුලිත සමීකරණ තුනක් ලියන්න.","2Na + 2H₂O → 2NaOH + H₂; 2Na + O₂ → Na₂O₂; K + O₂ → KO₂. ප්‍රතික්‍රියාශීලීතාව K වැඩිය.","Compare Na and K reactions with water and oxygen. Give three balanced equations.","நீருடனும் O₂ உடனும் Na, K தாக்கங்களை ஒப்பிட்டு மூன்று சமப்படுத்திய சமன்பாடுகளை எழுதுக."],
["MgCO₃ සහ BaCO₃ තාප ස්ථායීතාව සංසන්දනය කර හේතුව පැහැදිලි කරන්න.","Mg²⁺ හි ආරෝපණ ඝනත්වය ඉහළ නිසා CO₃²⁻ වැඩි ධ්‍රැවීකරණය; MgCO₃ පහසුවෙන් වියෝජනය වේ.","Compare MgCO₃/BaCO₃ thermal stability.","MgCO₃, BaCO₃ வெப்ப நிலைத்தன்மைகளை ஒப்பிடுக."],
["Al(OH)₃ උභයගුණී බව තහවුරු කරන ප්‍රතික්‍රියා දෙකක් ලියන්න.","Al(OH)₃ + 3H⁺ → Al³⁺ + 3H₂O; Al(OH)₃ + OH⁻ → [Al(OH)₄]⁻.","Show amphoterism of Al(OH)₃ with equations.","Al(OH)₃ இருபண்பைச் சமன்பாடுகளுடன் விளக்குக."],
["දියමන්ති හා මිනිරන් අතර බන්ධන, ව්‍යුහ හා සන්නායකතාව වෙනස්කම් සසඳන්න.","Diamond sp³ 3D covalent; graphite sp² layered, delocalized π electrons conduct.","Compare diamond and graphite structure, bonding and conductivity.","வைரம், கிராஃபைட்டு பிணைப்பு, வடிவம், மின்கடத்துதிறன் ஒப்பிடுக."],
["තනුක හා සාන්ද්‍ර HNO₃ සමඟ Cu ප්‍රතික්‍රියා ලියා NO, NO₂ වෙනස්කම සඳහන් කරන්න.","3Cu + 8HNO₃(dil) → 3Cu(NO₃)₂ + 2NO + 4H₂O; Cu + 4HNO₃(conc) → Cu(NO₃)₂ + 2NO₂ + 2H₂O.","Write Cu reactions with dilute and concentrated HNO₃.","தளர்ந்த, செறிந்த HNO₃ உடனான Cu தாக்கங்களை எழுதுக."],
["H₂O₂ ඔක්සිකාරකයක් හා ඔක්සිහාරකයක් වන ආකාරය දෙකකින් සනාථ කරන්න.","H₂O₂ + 2H⁺ + 2I⁻ → I₂ + 2H₂O; 2MnO₄⁻ + 5H₂O₂ + 6H⁺ → 2Mn²⁺ + 5O₂ + 8H₂O.","Demonstrate oxidizing and reducing behaviour of H₂O₂.","H₂O₂ ஒட்சியேற்றியும் குறைப்பானுமாகச் செயற்படுவதை விளக்குக."],
["Cl⁻, Br⁻, I⁻ හඳුනාගැනීමට AgNO₃/NH₃ පරීක්ෂාව විස්තර කරන්න.","AgCl සුදු/තනුක NH₃ දියවේ; AgBr ලා කහ/සාන්ද්‍ර NH₃ දියවේ; AgI කහ/නොදියවේ.","Describe silver nitrate and ammonia tests of halides.","Cl⁻, Br⁻, I⁻ இற்கான AgNO₃/NH₃ சோதனைகளை விளக்குக."],
["XeF₂, XeF₄, XeO₄ සඳහා Xe ඔක්සිකරණ අංක සොයන්න.","XeF₂ +2; XeF₄ +4; XeO₄ +8.","Determine Xe oxidation states in three compounds.","XeF₂, XeF₄, XeO₄ இல் Xe ஒட்சியேற்ற நிலைகளை காண்க."],
["Na₂O සිට Cl₂O₇ දක්වා ඔක්සයිඩවල ආම්ලික/භාෂ්මික වෙනස පැහැදිලි කරන්න.","Na₂O/MgO භාෂ්මික; Al₂O₃ උභයගුණී; SiO₂ දුබල ආම්ලික; P₄O₁₀/SO₃/Cl₂O₇ ආම්ලික.","Explain acid-base changes in Period 3 oxides.","மூன்றாம் ஆவர்த்தன ஒட்சைடுகளின் அமில/கார மாற்றங்களை விளக்குக."],
["CrO₄²⁻/Cr₂O₇²⁻ සමතුලිතතාව සහ Cu²⁺ + NH₃ වර්ණ වෙනස විස්තර කරන්න.","2CrO₄²⁻ + 2H⁺ ⇌ Cr₂O₇²⁻ + H₂O; කහ↔තැඹිලි. Cu²⁺ නිල්→අතිරික්ත NH₃ සමඟ තද නිල්.","Explain chromate–dichromate and copper–ammine colour changes.","குரோமேட்டு–இருகுரோமேட்டு மற்றும் Cu²⁺–NH₃ நிற மாற்றங்களை விளக்குக."]
];
window.U6_ESSAY=[
["s ගොනුවේ පළමු හා දෙවන කාණ්ඩවල ප්‍රතික්‍රියාශීලීතාව, ලවණවල තාප ස්ථායීතාව සහ ද්‍රාව්‍යතාව විස්තර කරන්න.","Group 1 vs 2: ns¹/ns²; +1/+2; reaction with water; nitrate/carbonate decomposition; sulfate/hydroxide solubility; Li/Be anomalies.","Compare Group 1 and Group 2 trends in reactivity, thermal stability and solubility.","தொகுதி 1 மற்றும் 2 வினைத்திறன், வெப்ப நிலைத்தன்மை, கரைதிறன் போக்குகளை விவாதிக்கவும்."],
["13–16 වන කාණ්ඩවල විශේෂිත සංයෝග යොදාගෙන උභයගුණීත්වය, බහුරූපීතාව සහ ඔක්සිකරණ–ඔක්සිහරණය පැහැදිලි කරන්න.","Al(OH)₃ amphoteric; diamond/graphite/C₆₀; HNO₃ oxidation; H₂O₂ dual redox; sulfur oxyacids.","Discuss amphoterism, allotropy and redox with Group 13–16 examples.","13–16 தொகுதிகளின் எடுத்துக்காட்டுகளுடன் இருபண்பு, புறவேற்றுமை, ஏற்றம்–இறக்கம் விவாதிக்கவும்."],
["17 හා 18 වන කාණ්ඩවල විද්‍යුත් වින්‍යාසය, ප්‍රතික්‍රියා සහ සරල සංයෝග සාකච්ඡා කරන්න.","Halogen displacement and H-X acidity; AgX test; Cl₂ disproportionation; noble gas inertness; XeF₂/XeF₄/XeF₆/XeO₄.","Discuss electronic structure, reactions and compounds of Groups 17 and 18.","17 மற்றும் 18 தொகுதிகளின் இலத்திரன் அமைப்பு, தாக்கங்கள், சேர்மங்கள் விவாதிக்கவும்."],
["තුන්වන ආවර්තයේ ඔක්සයිඩ, හයිඩ්‍රොක්සයිඩ හා ක්ලෝරයිඩවල ස්වභාවය Na සිට Cl දක්වා සසඳන්න.","Na₂O/MgO basic; Al₂O₃ amphoteric; SiO₂–Cl₂O₇ acidic; hydroxide/hydride trend; chloride hydrolysis.","Compare oxides, hydroxides and chlorides across Period 3.","மூன்றாம் ஆவர்த்தன ஒட்சைடுகள், ஐதரொட்சைடுகள், குளோரைடுகள் ஒப்பிடுக."],
["d ගොනුවේ විචල්‍ය ඔක්සිකරණ අංක, සංකීර්ණ සංයෝග, වර්ණ හා හඳුනාගැනීමේ පරීක්ෂණ සාකච්ඡා කරන්න.","dⁿ occupancy; Fe/Cu/Mn oxidation; CrO₄²⁻↔Cr₂O₇²⁻; MnO₄⁻; ligand complexes; Cu + excess NH₃; Fe³⁺ + SCN⁻.","Discuss variable oxidation states, complexes, colours and tests of d-block elements.","d கட்டத் தனிமங்களின் மாறும் ஒட்சியேற்ற நிலைகள், அணைவுகள், நிறங்கள், அடையாளச் சோதனைகள்." ]
];