/* Unit 06 learning application. No external JavaScript dependencies. */
(function(){
"use strict";
const chapters=window.U6_CHAPTERS,structured=window.U6_STRUCTURED,essays=window.U6_ESSAY;
if(!chapters||chapters.length!==10){document.getElementById("u6app").textContent="Unit 06 content could not load. Please refresh.";return;}
const lex={
si:{title:"s, p හා d ගොනුවල මූලද්‍රව්‍යවල රසායනය",sub:"NIE 12 ශ්‍රේණිය රසායන විද්‍යා සම්පත් පොත අනුව සකස් කළ ඉගෙනුම් සාරාංශය. නිරවද්‍ය සමීකරණ, සත්‍ය විද්‍යාත්මක ඡායාරූප, සිංහල වීඩියෝ සහ ප්‍රශ්න සමඟ සංකල්පයෙන් සංකල්පයට ඉදිරියට යන්න.",source:"NIE සම්පත් පොතේ මුද්‍රිත පිටු 125–179",lesson:"පාඩම් ගමන",mcq:"බහුවරණ ප්‍රශ්න",structured:"ව්‍යුහගත ප්‍රශ්න",essay:"රචනා ප්‍රශ්න",start:"ඉගෙනීම අරඹන්න",question:"ප්‍රශ්න අභ්‍යාස",based:"මූලාශ්‍රය",concept:"මූලික සංකල්පය",explore:"පියවරෙන් පියවර විග්‍රහය",pages:"මුද්‍රිත පිටු",photo:"සත්‍ය විද්‍යාත්මක ඡායාරූපය",photoSrc:"රූපයේ මූලාශ්‍රය සහ බලපත්‍රය",video:"සිංහල වීඩියෝ පාඩම",watch:"YouTube වෙත පිවිසෙන්න",quiz:"කොටස අවසාන පරීක්ෂාව",quizinfo:"ප්‍රශ්න 5න් අවම වශයෙන් 4ක් නිවැරදි නම් ඊළඟ කොටස විවෘත වේ.",check:"පිළිතුරු පරීක්ෂා කරන්න",retry:"නැවත උත්සාහ කරන්න",correct:"නිවැරදි",pass:"අභිනන්දන! ඊළඟ කොටස විවෘතයි.",fail:"ලකුණු 4ක් අවශ්‍යයි. සාරාංශය නැවත කියවා උත්සාහ කරන්න.",locked:"පෙර කොටසේ පරීක්ෂාව සමත් වූ පසු මෙය විවෘත වේ.",completed:"සම්පූර්ණ කළ කොටස්",unlocked:"විවෘත කොටස්",safety:"ආරක්ෂාව: විෂ වායු, ක්ෂාර ලෝහ, සාන්ද්‍ර අම්ල හා ඔක්සිකාරක පිළිබඳ ක්‍රියාවන් විදුහල් පරීක්ෂණාගාරයක සුදුසු අධීක්ෂණයකින් තොරව කිසිවිටක සිදු නොකරන්න.",origin:"මෙම සටහන් NIE පොතේ කරුණු අධ්‍යයනය කර නැවත ලියන ලද අධ්‍යාපනික සාරාංශයකි; විභාග ප්‍රශ්න ආදර්ශ ප්‍රශ්න වන අතර අතීත විභාග ප්‍රශ්න වචනානුසාරයෙන් උපුටා ගත් ඒවා නොවේ.",answer:"ආදර්ශ පිළිතුරු ලකුණු",reveal:"ආදර්ශ පිළිතුර බලන්න",pick:"කාණ්ඩය තෝරන්න",all:"සියලු කාණ්ඩ",examready:"ඒකක අවසාන බහුවරණ අභ්‍යාසය",examinfo:"කොටස් 10 ඇසුරින් සකස් කළ ප්‍රශ්න 50ක්. මෙය ඉගෙනුම පරීක්ෂා කරන ආදර්ශ ප්‍රශ්න පද්ධතියකි.",showanswer:"පිළිතුරු හා පැහැදිලි කිරීම",allOpen:"නව ඒකකයේ සියලු සාරාංශ කියවීමට මුලින්ම කොටස් 10 පහතින් ඇත; ඉදිරියට යාමට පරීක්ෂාව සමත් වන්න."},
en:{title:"Chemistry of s-, p- and d-block elements",sub:"A Grade 12 NIE-aligned learning journey with clear explanations, balanced reactions, scientific photographs, supplementary Sinhala video lessons and self-assessment.",source:"NIE Resource Book, printed pp. 125–179",lesson:"Lesson journey",mcq:"Multiple choice",structured:"Structured questions",essay:"Essay questions",start:"Start learning",question:"Practice questions",based:"Source",concept:"Key concept",explore:"Step-by-step explanation",pages:"Printed pages",photo:"Scientific photograph",photoSrc:"Image source and license",video:"Sinhala video lesson",watch:"Open on YouTube",quiz:"Section checkpoint",quizinfo:"Score at least 4 out of 5 to unlock the next section.",check:"Check answers",retry:"Try again",correct:"Correct",pass:"Well done! The next section is unlocked.",fail:"You need 4 marks. Review the notes and retry.",locked:"Pass the previous section's checkpoint to unlock this.",completed:"Sections completed",unlocked:"Sections unlocked",safety:"Safety: Do not attempt work with toxic gases, alkali metals, concentrated acids or oxidizers without appropriate laboratory supervision.",origin:"These are original study summaries based on the NIE book. Practice questions are newly written, not verbatim past-paper questions.",answer:"Marking guide",reveal:"Show model answer",pick:"Select section",all:"All sections",examready:"Whole-unit MCQ practice",examinfo:"50 original questions covering all 10 sections.",showanswer:"Answers and explanations",allOpen:"Study the 10 chapters below and pass each checkpoint to continue."},
ta:{title:"s, p மற்றும் d கட்டத் தனிமங்களின் வேதியியல்",sub:"தரம் 12 NIE வளநூல் அடிப்படையிலான பாடப் பயணம். விளக்கங்கள், சமப்படுத்திய சமன்பாடுகள், உண்மையான அறிவியல் படங்கள், சிங்கள காணொளிகள், பயிற்சி வினாக்கள்.",source:"NIE வளநூல், அச்சுப் பக்கங்கள் 125–179",lesson:"பாடப் பயணம்",mcq:"பல்தேர்வு வினாக்கள்",structured:"கட்டமைப்பு வினாக்கள்",essay:"கட்டுரை வினாக்கள்",start:"கற்கத் தொடங்குக",question:"பயிற்சி வினாக்கள்",based:"மூலம்",concept:"முக்கிய கருத்து",explore:"படிப்படியான விளக்கம்",pages:"அச்சுப் பக்கங்கள்",photo:"உண்மையான அறிவியல் படம்",photoSrc:"பட மூலம் / உரிமம்",video:"சிங்கள காணொளிப் பாடம்",watch:"YouTube இல் பார்க்கவும்",quiz:"பிரிவு மதிப்பீடு",quizinfo:"5 வினாக்களில் 4 சரியானால் அடுத்த பிரிவு திறக்கும்.",check:"விடைகளைச் சரிபார்க்கவும்",retry:"மீண்டும் முயல்க",correct:"சரி",pass:"நன்று! அடுத்த பிரிவு திறக்கப்பட்டது.",fail:"4 மதிப்பெண்கள் தேவை. மீண்டும் முயல்க.",locked:"முந்தைய பிரிவு மதிப்பீட்டில் தேர்ச்சி பெற்றபின் திறக்கும்.",completed:"முடித்த பிரிவுகள்",unlocked:"திறந்த பிரிவுகள்",safety:"பாதுகாப்பு: நச்சு வாயுக்கள், கார உலோகங்கள், செறிந்த அமிலங்கள், ஒட்சியேற்றிகள் ஆகியவற்றுடன் ஆய்வக மேற்பார்வையின்றி செயற்பட வேண்டாம்.",origin:"இவை NIE வளநூல் அடிப்படையிலான புதிய சுருக்கக் குறிப்புகள். வினாக்கள் அசல் கடந்தகாலத் தேர்வுக் கேள்விகளின் நேரடிப் பிரதிகள் அல்ல.",answer:"மதிப்பீட்டு வழிகாட்டி",reveal:"மாதிரி விடை",pick:"பிரிவைத் தெரிவுசெய்க",all:"அனைத்தும்",examready:"முழு அலகு பல்தேர்வு பயிற்சி",examinfo:"10 பிரிவுகளில் இருந்து 50 புதிய வினாக்கள்.",showanswer:"விடைகளும் விளக்கங்களும்",allOpen:"கீழே உள்ள 10 பிரிவுகளையும் படித்து ஒவ்வொரு மதிப்பீட்டையும் நிறைவேற்றுக."}
};
const keys=["si","en","ta"];let lang=keys.includes(localStorage.getItem("chem-lang"))?localStorage.getItem("chem-lang"):"si";
let tab="lesson",selected=0,results={},attempts={},examSection="all",examAnswers={},examGraded=false;
function loadDone(){try{let x=JSON.parse(localStorage.getItem("chem-u6-mastered")||"[]");return Array.isArray(x)?x.filter(i=>Number.isInteger(i)&&i>=0&&i<10):[]}catch(e){return[]}}
let passed=loadDone();
function unlocked(){let n=0;while(passed.includes(n)&&n<10)n++;return n}
function T(){return lex[lang]}function li(){return keys.indexOf(lang)}function txt(v){return Array.isArray(v)?v[li()]||v[0]:String(v||"")}
function esc(s){return String(s??"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[x]))}
function commonsLink(file){return "https://commons.wikimedia.org/wiki/File:"+encodeURIComponent(file).replace(/%20/g,"_")}
function commonsImg(file){return "https://commons.wikimedia.org/wiki/Special:FilePath/"+encodeURIComponent(file)+"?width=960"}
function pnum(n){return String(n+1).padStart(2,"0")}
function qopt(a){
 if(lang==="si")return a;
 if(a.includes(" / ")){
  const en=a.split(" / ").slice(-1)[0];
  if(lang==="en")return en;
  const t={"red":"சிவப்பு","yellow":"மஞ்சள்","green":"பச்சை","blue":"நீலம்","purple":"ஊதா","orange":"செம்மஞ்சள்","white":"வெள்ளை","crimson":"கருஞ்சிவப்பு","lilac":"ஊதா","yellow-green":"மஞ்சள்-பச்சை","increases":"அதிகரிக்கும்","decreases":"குறையும்","unchanged":"மாறாது","random":"ஒழுங்கற்ற","isotopes":"ஓரிடத்தான்கள்","allotropes":"புறவேற்றுமை வடிவங்கள்","ions":"அயன்கள்","isomers":"சமவகைகள்","linear":"நேர்கோட்டு","square planar":"சதுரத் தள","bent":"வளைந்த","tetrahedral":"நான்முகி","trigonal":"முக்கோண","square":"சதுரம்","deep blue":"ஆழ்நீலம்","colourless":"நிறமற்ற"};return t[en]||en;
 }
 const map={
  "sp³ නිසා":["because of sp³ bonds","sp³ பிணைப்பால்"],"විස්ථානගත π e⁻ නිසා":["due to delocalized π electrons","பரவலான π இலத்திரன்களால்"],"H බන්ධන නිසා":["because of hydrogen bonds","ஐதரசன் பிணைப்பால்"],"අයන නිසා":["because of ions","அயன்களால்"],
  "විෂ රහිතයි":["non-toxic","நச்சற்றது"],"අතිශය විෂයි":["highly toxic","மிக நச்சுடையது"],"කහ පාටයි":["yellow in colour","மஞ்சள் நிறம்"],"H₂ අඩංගුයි":["contains H₂","H₂ கொண்டுள்ளது"],
  "තනුකයේ දියවේ":["soluble in dilute ammonia","தளர்ந்த அமோனியாவில் கரையும்"],"සාන්ද්‍රයේ දියවේ":["soluble in concentrated ammonia","செறிந்த அமோனியாவில் கரையும்"],"සාමාන්‍යයෙන් නොදියවේ":["normally insoluble","பொதுவாகக் கரையாது"],"වායුවක් නිපදේ":["produces gas","வாயு வெளியேறும்"],
  "දිවිපරමාණුක":["diatomic","ஈரணு"],"ඒකපරමාණුක":["monatomic","தனி அணு"],"දැල් සහසංයුජ":["giant covalent network","பெரும் சகபிணைப்பு வலை"],"අයනික ඝන":["ionic solids","அயனிக் திண்மம்"],
  "ශූන්‍ය වේ":["becomes zero","பூச்சியமாகும்"],"d¹⁰ වින්‍යාසය":["d¹⁰ configuration","d¹⁰ அமைப்பு"],"+7 අංකය":["+7 oxidation state","+7 ஒட்சியேற்ற நிலை"],"වායුමය නිසා":["because it is a gas","வாயுவாதலால்"]
 };
 if(map[a])return map[a][lang==="en"?0:1];
 return a.replace(/ පමණි/g,lang==="ta"?" மட்டும்":" only");
}
function modelAnswer(a,i,type){
 if(lang==="si")return a[1];
 let related=type==="structured"?[chapters[i]]:[chapters[2*i],chapters[2*i+1]];
 return related.flatMap(c=>c.steps.map(step=>txt(step.d))).join(" • ");
}
function hero(){let u=T(),done=passed.length,un=Math.min(10,unlocked()+1);return '<section class="hero"><div class="wrap"><div class="eyebrow">NIE • GRADE 12 • UNIT 06 • INORGANIC CHEMISTRY</div><h1><span class="gradient">'+esc(u.title)+'</span></h1><p>'+esc(u.sub)+'</p><div class="chips"><span>10 '+(lang==="si"?"කොටස්":lang==="ta"?"பிரிவுகள்":"chapters")+'</span><span>'+chapters.reduce((n,c)=>n+c.steps.length,0)+' '+(lang==="si"?"විග්‍රහයන්":lang==="ta"?"விளக்கங்கள்":"concept notes")+'</span><span>50 MCQ</span><span>10 '+(lang==="si"?"ව්‍යුහගත":lang==="ta"?"கட்டமைப்பு":"structured")+'</span><span>5 '+(lang==="si"?"රචනා":lang==="ta"?"கட்டுரை":"essay")+'</span></div><div class="heroactions"><button class="btn primary" type="button" data-view="lesson">'+esc(u.start)+' ↓</button><button class="btn" type="button" data-view="mcq">'+esc(u.question)+' →</button></div></div></section><section class="wrap"><div class="dash"><div class="dashrow"><div><strong>'+esc(u.completed)+' <span>'+done+'/10</span></strong><div><small>'+esc(u.unlocked)+': '+un+'/10</small></div></div><span class="pct">'+Math.round(done*10)+'%</span></div><div class="progressbar"><i style="width:'+(done*10)+'%"></i></div><small>'+esc(u.source)+'</small></div></section>'}
function nav(){return '<nav class="unitTabs wrap" aria-label="Unit 06"><button type="button" data-view="lesson" class="tab '+(tab==="lesson"?"on":"")+'">'+esc(T().lesson)+'</button><button type="button" data-view="mcq" class="tab '+(tab==="mcq"?"on":"")+'">'+esc(T().mcq)+'</button><button type="button" data-view="structured" class="tab '+(tab==="structured"?"on":"")+'">'+esc(T().structured)+'</button><button type="button" data-view="essay" class="tab '+(tab==="essay"?"on":"")+'">'+esc(T().essay)+'</button></nav>'}
function jumps(){return '<div class="jump">'+chapters.map((c,i)=>'<button data-jump="'+i+'" type="button" class="'+(passed.includes(i)?"done":i>unlocked()?"locked":"")+'"><b>'+pnum(i)+'</b>'+esc(txt(c.name))+' '+(passed.includes(i)?"✓":i>unlocked()?"🔒":"")+'</button>').join("")+'</div>'}
function photo(file,step){return '<figure class="realPhoto" style="margin:0" data-photo-holder><img loading="lazy" alt="'+esc(txt(step.t))+'" src="'+commonsImg(file)+'" onerror="this.closest(\'[data-photo-holder]\').classList.add(\'photoBroken\')"><div class="photoFallback" aria-hidden="true">'+esc(step.eq.split(" | ")[0])+'</div></figure><small class="photoCredit"><a href="'+commonsLink(file)+'" target="_blank" rel="noopener noreferrer">'+esc(T().photoSrc)+' ↗</a> · Wikimedia Commons</small>'}
function stepBlock(step,i,j,c){let file=c.photos[j%c.photos.length];return '<div class="step"><article class="stepbox"><div class="stepinfo"><small class="stepidx">'+esc(T().concept)+' · '+pnum(j)+'</small><h3>'+esc(txt(step.t))+'</h3><p>'+esc(txt(step.d))+'</p><div class="equation">'+esc(step.eq)+'</div></div>'+photo(file,step)+'</article></div>'}
function video(c){if(!c.video)return "";const id=encodeURIComponent(c.video),u=T();return '<aside class="videoBox"><iframe loading="lazy" allowfullscreen title="'+esc(u.video)+'" referrerpolicy="strict-origin-when-cross-origin" src="https://www.youtube-nocookie.com/embed/'+id+'" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"></iframe><div><small class="eyebrow">DP EDUCATION • සිංහල මාධ්‍යය</small><h3>'+esc(u.video)+'</h3><p>'+esc(txt(c.name))+'</p><a href="https://www.youtube.com/watch?v='+id+'" target="_blank" rel="noopener noreferrer">'+esc(u.watch)+' ↗</a></div></aside>'}
function makeQuiz(c,i){let prev=attempts[i]||{},graded=results[i],u=T();return '<div class="checkpoint" data-checkpoint="'+i+'"><small>05 QUESTIONS • 04 PASS MARKS</small><h3>'+esc(u.quiz)+'</h3><p class="smallNote">'+esc(u.quizinfo)+'</p>'+c.qs.map((q,k)=>'<div class="quizItem"><strong>'+pnum(k)+' · '+esc(q[li()])+'</strong><div class="answers">'+q[3].map((opt,z)=>{let sel=prev[k]===z,cls=graded&&z===q[4]?" right":graded&&sel&&z!==q[4]?" wrong":sel?" chosen":"";return '<button type="button" data-chk-pick="'+i+'|'+k+'|'+z+'" '+(graded?"disabled":"")+' class="'+cls+'">'+esc(qopt(opt))+'</button>'}).join("")+'</div>'+(graded?'<div class="explanation">'+(lang==="si"?esc(q[5]):(lang==="ta"?"சரியான விடை: ":"Correct answer: ")+esc(qopt(q[3][q[4]])))+'</div>':"")+'</div>').join("")+'<div class="results">'+(graded?'<b class="'+(graded.score>=4?"gateOk":"gateBad")+'">'+graded.score+'/5 — '+esc(graded.score>=4?u.pass:u.fail)+'</b><button class="btn" data-reset-check="'+i+'">'+esc(u.retry)+'</button>':'<button class="btn primary" data-check-submit="'+i+'" '+(Object.keys(prev).length!==5?"disabled":"")+'>'+esc(u.check)+'</button>')+'</div></div>'}
function chapter(c,i){if(i>unlocked())return '<section class="chapter lockedChapter" id="u6chapter'+i+'"><span class="lock">🔒</span><div><small>NIE '+esc(c.ref)+'</small><h2>'+esc(txt(c.name))+'</h2><p>'+esc(T().locked)+'</p></div></section>';return '<section class="chapter" id="u6chapter'+i+'"><header class="chapterHead"><small>UNIT 06 · '+esc(c.ref)+' · '+esc(T().pages)+' '+esc(c.pages)+' · '+pnum(i)+'/10</small><h2>'+esc(txt(c.name))+'</h2><p>'+esc(txt(c.intro))+'</p></header><div class="route">'+c.steps.map((s,j)=>stepBlock(s,i,j,c)).join("")+'</div><div class="cardFoot"><span class="smallNote">NIE Grade 12 · Unit 06 · '+esc(c.ref)+'</span><span class="smallNote">4 '+esc(T().concept)+'</span></div>'+video(c)+makeQuiz(c,i)+'</section>'}
function journey(){return '<section class="wrap"><div class="unitIntro"><strong>'+esc(T().based)+' • '+esc(T().source)+'</strong><p>'+esc(T().origin)+'</p><p>'+esc(T().safety)+'</p></div>'+jumps()+'<div class="chapters">'+chapters.map(chapter).join("")+'</div></section>'}
function singleQ(q,id,form,graded){let answers=form[id];return '<div class="quizItem"><strong>'+esc(id.split("-").join(". "))+' · '+esc(q[li()])+'</strong><div class="answers">'+q[3].map((opt,z)=>'<button '+(graded?"disabled":"")+' type="button" data-ex-pick="'+id+'|'+z+'" class="'+(graded&&z===q[4]?"right":graded&&answers===z?"wrong":answers===z?"chosen":"")+'">'+esc(qopt(opt))+'</button>').join("")+'</div>'+(graded?'<div class="explanation">'+(lang==="si"?esc(q[5]):(lang==="ta"?"சரியான விடை: ":"Correct answer: ")+esc(qopt(q[3][q[4]])))+'</div>':"")+'</div>'}
function exam(){let u=T(),sections=examSection==="all"?chapters.map((c,i)=>[c,i]):[[chapters[+examSection],+examSection]],list=sections.flatMap(([c,i])=>c.qs.map((q,j)=>[q,i,j])),score=list.reduce((n,[q,i,j])=>n+(examAnswers[i+"-"+j]===q[4]?1:0),0),allAns=list.every(([q,i,j])=>Number.isInteger(examAnswers[i+"-"+j]));return '<section class="wrap examPanel"><div class="unitIntro"><strong>'+esc(u.examready)+'</strong><p>'+esc(u.examinfo)+'</p></div><div class="toolbar"><label for="examUnit6">'+esc(u.pick)+'</label><select id="examUnit6"><option value="all" '+(examSection==="all"?"selected":"")+'>'+esc(u.all)+' · 50 MCQ</option>'+chapters.map((c,i)=>'<option value="'+i+'" '+(examSection==i?"selected":"")+'>'+pnum(i)+' · '+esc(txt(c.name))+'</option>').join("")+'</select></div><div class="examBig">'+list.map(([q,i,j])=>singleQ(q,(i+"-"+j),examAnswers,examGraded)).join("")+'</div><div class="results"><button class="btn primary" data-ex-submit '+(!allAns||examGraded?"disabled":"")+'>'+esc(u.check)+'</button><button class="btn" data-ex-reset>'+esc(u.retry)+'</button><b>'+ (examGraded?score+" / "+list.length:"")+'</b></div></section>'}
function questions(type){let u=T(),bank=type==="structured"?structured:essays;return '<section class="wrap examPanel"><div class="unitIntro"><strong>'+esc(type==="structured"?u.structured:u.essay)+'</strong><p>'+esc(u.origin)+'</p></div>'+bank.map((a,i)=>'<article class="testCard"><small>'+(type==="structured"?chapters[i].ref:pnum(i))+' · '+(type==="structured"?"STRUCTURED":"ESSAY")+'</small><h3>'+(lang==="si"?esc(a[0]):esc(a[li()+1]))+'</h3><details><summary>'+esc(u.reveal)+'</summary><p class="model">'+esc(modelAnswer(a,i,type))+'</p></details></article>').join("")+'</section>'}
function applyHeader(){document.documentElement.lang=lang;document.querySelectorAll("[data-u6-lang]").forEach(b=>{b.classList.toggle("active",b.dataset.u6Lang===lang);b.setAttribute("aria-pressed",String(b.dataset.u6Lang===lang))});let names=lang==="si"?["මුල් පිටුව","ඒකක","ප්‍රායෝගිකාගාරය"]:lang==="ta"?["முகப்பு","அலகுகள்","மெய்நிகர் ஆய்வகம்"]:["Home","Units","Virtual Lab"];["backHome","backUnits","backLab"].forEach((id,i)=>document.getElementById(id).textContent=names[i]);document.title="Unit 06 • "+T().title}
function render(){applyHeader();document.getElementById("u6app").innerHTML=hero()+nav()+(tab==="lesson"?journey():tab==="mcq"?exam():questions(tab));wire()}
function scrolly(el){requestAnimationFrame(()=>document.querySelector(el)?.scrollIntoView({behavior:"smooth",block:"start"}))}
function wire(){
document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>{tab=b.dataset.view;render();scrolly(tab==="lesson"?".unitIntro":".unitTabs")}));
document.querySelectorAll("[data-jump]").forEach(b=>b.addEventListener("click",()=>{let i=+b.dataset.jump;scrolly("#u6chapter"+i)}));
document.querySelectorAll("[data-chk-pick]").forEach(b=>b.addEventListener("click",()=>{let [i,j,k]=b.dataset.chkPick.split("|").map(Number);if(results[i])return;attempts[i]=attempts[i]||{};attempts[i][j]=k;document.querySelectorAll('[data-chk-pick^="'+i+'|'+j+'|"]').forEach(x=>x.classList.toggle("chosen",x===b));let submit=document.querySelector('[data-check-submit="'+i+'"]');if(submit)submit.disabled=Object.keys(attempts[i]).length!==5}));
document.querySelectorAll("[data-check-submit]").forEach(b=>b.addEventListener("click",()=>{let i=+b.dataset.checkSubmit,a=attempts[i]||{};if(Object.keys(a).length!==5)return;let score=chapters[i].qs.reduce((n,q,j)=>n+(a[j]===q[4]?1:0),0);results[i]={score};if(score>=4&&!passed.includes(i)){passed.push(i);localStorage.setItem("chem-u6-mastered",JSON.stringify(passed))}let y=window.scrollY;render();window.scrollTo(0,y);scrolly('[data-checkpoint="'+i+'"]')}));
document.querySelectorAll("[data-reset-check]").forEach(b=>b.addEventListener("click",()=>{let i=+b.dataset.resetCheck;delete results[i];delete attempts[i];let y=window.scrollY;render();window.scrollTo(0,y);scrolly('[data-checkpoint="'+i+'"]')}));
let sel=document.getElementById("examUnit6");if(sel)sel.addEventListener("change",()=>{examSection=sel.value;examAnswers={};examGraded=false;render();scrolly(".examPanel")});
document.querySelectorAll("[data-ex-pick]").forEach(b=>b.addEventListener("click",()=>{let p=b.dataset.exPick.split("|"),idx=p[0],opt=+p[1];if(examGraded)return;examAnswers[idx]=opt;document.querySelectorAll('[data-ex-pick^="'+idx+'|"]').forEach(x=>x.classList.toggle("chosen",x===b));const needed=(examSection==="all"?50:5),submit=document.querySelector("[data-ex-submit]");if(submit)submit.disabled=Object.keys(examAnswers).length<needed}));
document.querySelectorAll("[data-ex-submit]").forEach(b=>b.addEventListener("click",()=>{examGraded=true;let y=window.scrollY;render();window.scrollTo(0,y);scrolly(".examPanel")}));
document.querySelectorAll("[data-ex-reset]").forEach(b=>b.addEventListener("click",()=>{examAnswers={};examGraded=false;render();scrolly(".examPanel")}));
}
document.querySelectorAll("[data-u6-lang]").forEach(b=>b.addEventListener("click",()=>{lang=b.dataset.u6Lang;localStorage.setItem("chem-lang",lang);render()}));
window.addEventListener("storage",e=>{if(e.key==="chem-u6-mastered"){passed=loadDone();render()}});
render();
})();